import { PortfolioType } from "@/@types/types";

const PortfolioData: Array<PortfolioType> = [
  {
    id: 1,
    title: "Mentor Mentee Connects",
    image: "https://res.cloudinary.com/dvdi2oaso/image/upload/v1730975152/Portfolio%20Assets/Group_79_ymxs3z.png",
    categories: ["Nodejs", "Go", "Typescript", "Mongodb", "Firebase", "Redis", "Jest", "Docker", "Kubernetes", "Terraform", "GCP", "VPC", "CICD", "Prometheus", "Grafana", "Loki"],
    col: 12,
    projectUrl: "https://play.google.com/store/apps/details?id=com.mentormenteeconnect.mentor_mentee_connects",
  },
  {
    id: 2,
    title: "Meal Diaries",
    image: "https://res.cloudinary.com/dvdi2oaso/image/upload/v1688570430/Portfolio%20Assets/mealDiaries2_rxal09.png",
    categories: ["Nodejs", "Mongodb", "Firebase", "Docker", "CICD", "Jest"],
    col: 12,
    projectUrl: "https://github.com/SEM5-MiniProject/Backend",
  },
  {
    id: 3,
    title: "Synapse",
    image: "https://res.cloudinary.com/dvdi2oaso/image/upload/v1688570430/Portfolio%20Assets/synapse_kmarm7.png",
    categories: [
      "Python",
      "ML",
      "MLOps",
      "Flask",
      "Docker",
      "CICD",
      "Firebase",
    ],
    col: 12,
    projectUrl: "https://github.com/siesgstarena/synapse",
  },
  {
    id: 4,
    title: "Arena 2.0",
    image: "https://res.cloudinary.com/dvdi2oaso/image/upload/v1688570429/Portfolio%20Assets/arena2_v59vg0.png",
    categories: ["React", "GraphQL", "Nodejs"],
    col: 12,
    projectUrl: "https://github.com/siesgstarena/Arena-2.0",
  },
  {
    id: 5,
    title: "Arena Bot",
    image: "https://res.cloudinary.com/dvdi2oaso/image/upload/v1688570429/Portfolio%20Assets/arenabot2_t9z8zk.png",
    categories: ["Nodejs", "Discord", "CICD", "Docker"],
    col: 6,
    projectUrl: "https://github.com/siesgstarena/Arena-bot",
  },
  {
    id: 6,
    title: "CP Bot",
    image: "https://res.cloudinary.com/dvdi2oaso/image/upload/v1688570429/Portfolio%20Assets/cpbot2_um57r8.png",
    categories: ["Python", "API", "Discord"],
    col: 6,
    projectUrl: "https://github.com/SalmanAd01/CP-Bot",
  },
  {
    id: 7,
    title: "UptimeX",
    image: "https://res.cloudinary.com/dvdi2oaso/image/upload/v1688570430/Portfolio%20Assets/uptimex_wrlvm3.png",
    categories: ["Nodejs", "Postgresql", "Heroku"],
    col: 12,
    projectUrl: "https://github.com/SalmanAd01/UptimeX",
  },
  {
    id: 8,
    title: "Raspberry Pi Attendance System",
    image: "https://res.cloudinary.com/dvdi2oaso/image/upload/v1688570430/Portfolio%20Assets/raspberry2_easdra.png",
    categories: ["Python", "Raspberry Pi", "Nodejs", "MongoDB", "Flutter"],
    col: 6,
    projectUrl: "https://github.com/SEM-6-MP2-0",
  },
  {
    id: 9,
    title: "Smart City",
    image: "https://res.cloudinary.com/dvdi2oaso/image/upload/v1688570430/Portfolio%20Assets/smartcity2_iueimq.png",
    categories: ["Java", "GUI", "Postgresql"],
    col: 6,
    projectUrl: "https://github.com/Smart-City-JavaProject/Javafx_Gui",
  },
  {
    id: 10,
    title: "BookHub",
    image: "https://res.cloudinary.com/dvdi2oaso/image/upload/v1688570429/Portfolio%20Assets/bookhub_xdalhx.png",
    categories: ["Go", "React", "Postgresql", "Docker", "CICD"],
    col: 12,
    projectUrl: "https://github.com/SalmanAd01/BookHub",
  },
];

export default PortfolioData;